### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by zapatoche** [thespacedojo/simple-form#1]
Would you happen to have  an example or docs about how to use it. I have vague memories from simple-form for rails and I'm new to the meteor thing :)

Cheers

**Comment by chmac** [comment]
See the docs http://github.differential.io/simple-form/

**Comment by queso** [comment]
Oh, thx for this, guess I missed the initial email asking for docs.

It isn't documented yet, but there is also a SimpleForm.processForm(event.target) which you can use for a submit event.  This project is still pretty infantile, but it has solid functionality now.
