### ISSUE TITLE
Add class name

### ISSUE THREAD

**Issue by ralphievolt** [thespacedojo/simple-form#24]
Adding a button is like this
       {{submit_button 'Add'}}

which generate a code below
      ' button type="submit" class="btn btn-primary">Add</button'

what if I wanted to add more class? Is this supported? I tried doing this way but its working
         button type="submit" class="btn btn-primary btnClick">Add</button

**Comment by paritoshbotre** [comment]
Yes @ralphievolt , you can add more classes by using the following syntax:

`{{submit_button 'Add' class='btnClick someCustomClass'}}`

which generates the following HTML:

`<input type="submit" value="Add" class="btn btn-default btnClick someCustomClass">`
